/** Ledger and Workshop homepage: the film is an optional opening note, while the page answers what ChipTech does, records, and needs. */
import { useState } from "react";
import { ArrowRight, ArrowUpRight, BadgeCheck, BookOpenCheck, CircuitBoard, ExternalLink, FileWarning, UsersRound } from "lucide-react";
import { Link } from "wouter";
import LandingExperience from "@/components/landing/LandingExperience";
import ClubLayout from "@/components/ClubLayout";
import SectionHeading from "@/components/SectionHeading";
import { buildBenchPrinciples, events, projects, teamGroups } from "@/lib/clubData";
import { track } from "@/lib/analytics";
import HeroReel from "@/components/HeroReel";
import NextWorkshopDocket from "@/components/NextWorkshopDocket";

const mark = "/manus-storage/chiptech-official-mark_91a6def1.jpg";
const heroLoop = "/manus-storage/chiptech-hero-loop_ce1b0b56.mp4";
const evidenceImage = "/manus-storage/chiptech-circuitrix-rvu-record_cb74090e.webp";

export default function Home() {
  const [showIntro, setShowIntro] = useState(() => window.localStorage.getItem("chiptech-intro-seen") !== "true" && new URLSearchParams(window.location.search).get("view") !== "home");
  const enterHomepage = () => {
    window.localStorage.setItem("chiptech-intro-seen", "true");
    setShowIntro(false);
    window.requestAnimationFrame(() => document.querySelector("#home")?.scrollIntoView({ behavior: "smooth", block: "start" }));
  };

  if (showIntro) return <div className="tactile-site"><div className="paper-grain" aria-hidden="true" /><LandingExperience onEnter={enterHomepage} onSkip={enterHomepage} /></div>;

  return <ClubLayout><section className="editorial-hero" id="home" aria-labelledby="index-hero-title"><HeroReel src={heroLoop} poster={evidenceImage} label="Electronics bench editorial reel" /><div className="editorial-film-grade" aria-hidden="true" /><div className="editorial-masthead"><span>CHIPTECH / FIELD EDITION</span><span>RV UNIVERSITY · BENGALURU</span><span>ISSUE 01 / BUILD CULTURE</span></div><div className="editorial-brand-artifact" aria-label="ChipTech, RV University Bengaluru"><img src={mark} alt="" /><div><strong>CHIP<span>TECH</span></strong><small>RVU / BLR · BUILD CULTURE</small></div><i /></div><div className="editorial-hero-copy"><p className="kicker">A STUDENT HARDWARE PUBLICATION</p><h1 id="index-hero-title">MAKE THE<br />SYSTEM <em>LEGIBLE.</em></h1><p>ChipTech is a technical community at RV University for students who want to learn circuits, embedded systems, hardware prototyping, and the practice of turning a test into a useful record.</p><div className="index-actions"><Link href="/projects">Open the project archive <ArrowRight size={18} /></Link><Link href="/join" onClick={() => track("join_cta_clicked", { placement: "editorial_hero" })}>Find the join route <ArrowUpRight size={18} /></Link></div></div><aside className="editorial-proof-docket"><span><BadgeCheck size={14} /> SOURCE DOCKET / 01</span><strong>Circuitrix: Light Up RVU</strong><time dateTime="2023-12-20">Published 20 Dec 2023</time><a href="https://rvu.edu.in/events/circuitrix-light-up-rvu/" target="_blank" rel="noreferrer">Read RVU record <ExternalLink size={15} /></a></aside><div className="editorial-issue-tag">THE<br />BUILD<br />BENCH</div><div className="editorial-scroll-cue"><i /> <span>Scroll for the record</span></div></section><NextWorkshopDocket />

    <section className="index-manifesto route-section"><SectionHeading serial="01 / BUILD BENCH" eyebrow="WHY CHIPTECH EXISTS" title={<>THE BENCH IS WHERE<br />IDEAS <em>GET HONEST.</em></>} detail="The club is not a claim about innovation. It is a place to make a signal path visible, test an assumption, and leave the next builder more context than you found." /><div className="principle-grid">{buildBenchPrinciples.map((principle) => <article key={principle.serial}><span>{principle.serial}</span><h2>{principle.title}</h2><p>{principle.detail}</p></article>)}</div></section>

    <section className="index-archive route-section"><div className="index-section-split"><SectionHeading serial="02 / BUILD ARCHIVE" eyebrow="WHAT THE CLUB HAS BUILT" title={<>SHOW THE BOARD.<br />SHOW THE <em>REVISION.</em></>} detail="The archive is deliberately conservative until official artifacts are released." /><div className="archive-route-links"><Link href="/projects" className="section-route">Browse archive <ArrowRight size={17} /></Link><Link href="/field-notes" className="section-route">Read visual field notes <ArrowRight size={17} /></Link></div></div><div className="index-archive-grid">{projects.map((project) => <article className="index-project-record" key={project.id}><div><span className="record-state"><FileWarning size={14} /> {project.status.replaceAll("_", " ")}</span><h2>{project.title}</h2><p>{project.summary}</p></div><dl><div><dt>Record category</dt><dd>{project.category}</dd></div><div><dt>Update state</dt><dd>{project.updatedAt}</dd></div></dl><div className="record-tags">{project.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div></article>)}<article className="archive-ask"><CircuitBoard size={28} /><h2>Have a board, trace, or field note?</h2><p>Approved project photography, repositories, and short technical notes can turn this record structure into a working archive.</p><Link href="/field-notes">Read the visual-study template <ArrowUpRight size={16} /></Link></article></div></section>

    <section className="index-ledger route-section"><div className="index-section-split"><SectionHeading serial="03 / WORKSHOP LEDGER" eyebrow="WHAT HAS HAPPENED" title={<>EACH EVENT LEAVES<br />A <em>TRAIL.</em></>} detail="The ledger starts with institutional records. Future programmes remain visibly pending until ChipTech publishes the details." /><Link href="/ledger" className="section-route">Read full ledger <ArrowRight size={17} /></Link></div><div className="index-ledger-grid"><figure className="ledger-image"><img src={evidenceImage} alt="RV University post documenting Circuitrix 2.0" /><figcaption>RVU RECORD / CIRCUITRIX 2.0</figcaption></figure><div className="ledger-record-list">{events.slice(0, 2).map((event) => <article key={event.id}><span>{event.dateLabel}</span><h2>{event.title}</h2><p>{event.summary}</p><a href={event.href} target="_blank" rel="noreferrer">Source record <ArrowUpRight size={15} /></a></article>)}</div></div></section>

    <section className="index-people route-section"><div className="people-matter"><UsersRound size={30} /><p className="kicker">PEOPLE AND PRACTICE</p><h2>BUILD WITH PEOPLE WHO KEEP <em>NOTES.</em></h2><p>ChipTech needs hands at the bench and hands on the documentation. The public roster is awaiting confirmation, but the working structure is already clear.</p><Link href="/people">Read the people structure <ArrowRight size={17} /></Link></div><div className="people-compact-list">{teamGroups.map((group, index) => <article key={group.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{group.title}</h3><p>{group.note}</p></div></article>)}</div></section>

    <section className="index-join"><div className="join-index-mark">CHIPTECH<br />WORKS<br />IN PUBLIC</div><div><p className="kicker">JOIN THE BUILD BENCH</p><h2>BRING A QUESTION.<br /><em>LEAVE A TRACE.</em></h2><p>Whether you are curious about a first circuit, an embedded system, a data sheet, a workshop, or a documentation problem, the club needs useful curiosity more than polished credentials.</p><Link href="/join" onClick={() => track("join_cta_clicked", { placement: "index_join" })}>Find the direct route <ArrowRight size={18} /></Link></div><aside><BookOpenCheck size={25} /><strong>Recruitment schedule</strong><span>Pending official publication</span></aside></section></ClubLayout>;
}
