/** People route: working structure and clear attribution gaps instead of invented roster cards. */
import { ArrowRight, BadgeCheck, CircleUserRound, UsersRound } from "lucide-react";
import { Link } from "wouter";
import ClubLayout from "@/components/ClubLayout";
import SectionHeading from "@/components/SectionHeading";
import { teamGroups } from "@/lib/clubData";

export default function People() {
  return <ClubLayout><section className="route-hero people-hero"><div className="route-mark">PEOPLE<br />03</div><SectionHeading serial="03 / PEOPLE AND PRACTICE" eyebrow="THE CIRCUIT IS ALSO SOCIAL" title={<>NO MAKER SPACE<br />WORKS <em>ALONE.</em></>} detail="This page provides the accountability structure behind ChipTech. Names and role details appear only after the club has confirmed them." /><div className="role-principles"><span><CircleUserRound size={19} /> Own a task</span><span><UsersRound size={19} /> Share the bench</span><span><BadgeCheck size={19} /> Document the handoff</span></div><aside className="route-evidence-docket"><span>ATTRIBUTION STATUS</span><strong>OFFICIAL ROSTER PENDING</strong><p>Names, roles, and consented public links are released only after club confirmation.</p><i>GAP LABEL / ACTIVE</i></aside></section><section className="route-section people-structure"><div className="people-intro"><p className="kicker">PUBLISHED STRUCTURE</p><h2>A role should say<br />what it <em>enables.</em></h2><p>Club membership should never feel like a private group chat with a soldering iron. The initial public structure below is intentionally modest, because the official roster is still awaiting confirmation.</p></div><div className="people-grid">{teamGroups.map((group, index) => <article key={group.title} className="role-card"><span>ROLE GROUP / {String(index + 1).padStart(2, "0")}</span><h3>{group.title}</h3><p>{group.note}</p><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section><section className="route-cta-strip"><div><span>OPEN CONTRIBUTION</span><h2>Bring a question, a failed prototype, or a useful skill.</h2></div><Link href="/join">Find the join path <ArrowRight size={18} /></Link></section></ClubLayout>;
}
