/** Project Archive route: credible project publishing structure that refuses to invent build claims. */
import { ArrowRight, BookOpenCheck, ExternalLink, FolderOpenDot, Wrench } from "lucide-react";
import { Link } from "wouter";
import ClubLayout from "@/components/ClubLayout";
import SectionHeading from "@/components/SectionHeading";
import { projects } from "@/lib/clubData";

export default function Projects() {
  return <ClubLayout><section className="route-hero route-archive"><div className="route-mark">ARCHIVE<br />01</div><SectionHeading serial="01 / PROJECT ARCHIVE" eyebrow="THE WORK, NOT THE MOODBOARD" title={<>BUILD RECORDS,<br /><em>OPENLY MARKED.</em></>} detail="A project page should state what was built, what changed, who contributed, and where the evidence lives. This archive is ready for those records." /><div className="archive-index"><div><Wrench size={25} /><strong>Artifact-first</strong><span>Photos, board revisions, scope traces, repositories, and test notes belong here.</span></div><div><BookOpenCheck size={25} /><strong>Learning-first</strong><span>Failures and fixes are part of the record, not a public-relations leak.</span></div><div><FolderOpenDot size={25} /><strong>Status-first</strong><span>Every entry carries a visible state. No mystery claims in a dark rectangle.</span></div></div></section><section className="route-section archive-records"><div className="record-callout"><p className="kicker">CURRENT ARCHIVE STATE</p><h2>THE FRAME EXISTS.<br />THE EVIDENCE IS <em>AWAITING RELEASE.</em></h2><p>ChipTech has not supplied official project names, contributor credits, repository links, or approved build photography for publication. This is therefore an honest indexed gap, not a fabricated launch portfolio.</p><a href="https://www.linkedin.com/company/chiptechrvu" target="_blank" rel="noreferrer">Follow published club updates <ExternalLink size={16} /></a></div><div className="archive-grid">{projects.map((project) => <article className="archive-card" key={project.id}><span className="archive-stamp">{project.status.replaceAll("_", " ")}</span><h3>{project.title}</h3><p>{project.summary}</p><dl><div><dt>Record class</dt><dd>{project.category}</dd></div><div><dt>Update state</dt><dd>{project.updatedAt}</dd></div></dl><div className="archive-tags">{project.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div></article>)}</div></section><section className="route-cta-strip"><div><span>CONTRIBUTOR ROUTE</span><h2>Have a build record to publish?</h2></div><Link href="/join">See how to contribute <ArrowRight size={18} /></Link></section></ClubLayout>;
}
